volumes:
  tailscale-state:
  spotipy-cache:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - '3000:3000'
    volumes:
      - tailscale-state:/var/lib/tailscale
      - spotipy-cache:/data/spotipy-cache
      - ${MUSIC_DIR}:/music
    environment:
      - TS_NAME=music-downloader
      - TS_AUTHKEY
      - TS_EXIT_NODE
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - GENIUS_ACCESS_TOKEN
    entrypoint: sh start.sh
