volumes:
  tailscale-state:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - tailscale-state:/var/lib/tailscale
      - ${MUSIC_DIR}:/music
    environment:
      - TS_NAME=music-downloader
      - TS_AUTHKEY
      - TS_EXIT_NODE
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - GENIUS_ACCESS_TOKEN
    entrypoint: sh start.sh
