volumes:
  tailscale-state:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - tailscale-state:/var/lib/tailscale
    environment:
      - TS_NAME=music-downloader
      - TS_AUTHKEY=${TS_AUTHKEY}
    entrypoint: sh start.sh
